export const iconMap = {
  react: 'i-skill-icons:react-light dark:i-skill-icons:react-dark',
  nodejs: 'i-skill-icons:nodejs-light dark:i-skill-icons:nodejs-dark',
  astro: 'i-skill-icons:astro',
  nextjs: 'i-skill-icons:nextjs-light dark:i-skill-icons:nextjs-dark',
  typescript: 'i-skill-icons:typescript',
  javascript: 'i-skill-icons:javascript',
  godot: 'i-skill-icons:godot-light dark:i-skill-icons:godot-dark',
  unity: 'i-skill-icons:unity-light dark:i-skill-icons:unity-dark',
  vitejs: 'i-skill-icons:vite-light dark:i-skill-icons:vite-dark',
  github: 'i-skill-icons:github-light dark:i-skill-icons:github-dark',
  githubactions: 'i-skill-icons:githubactions-light dark:i-skill-icons:githubactions-dark',
  git: 'i-skill-icons:git',
  redux: 'i-skill-icons:redux',
  solidjs: 'i-skill-icons:solidjs-light dark:i-skill-icons:solidjs-dark',
  netlify: 'i-skill-icons:netlify-light dark:i-skill-icons:netlify-dark',
  aws: 'i-skill-icons:aws-light dark:i-skill-icons:aws-dark',
  markdown: 'i-skill-icons:markdown-light dark:i-skill-icons:markdown-dark',
  tailwindcss: 'i-skill-icons:tailwindcss-light dark:i-skill-icons:tailwindcss-dark',
  blender: 'i-skill-icons:blender-light dark:i-skill-icons:blender-dark',
  svelte: 'i-skill-icons:svelte',
  vuejs: 'i-skill-icons:vuejs-light dark:i-skill-icons:vuejs-dark',
  python: 'i-skill-icons:python-light dark:i-skill-icons:python-dark'
} as const;
